### ISSUE TITLE
Typing does not support old python versions

### ISSUE THREAD

**Issue by AcerP-py** [olcf/velocity#19]
```
Traceback (most recent call last):
  File "/usr/lib64/python3.6/runpy.py", line 183, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/lib64/python3.6/runpy.py", line 142, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/usr/lib64/python3.6/runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "/ccs/home/xjv/.local/lib/python3.6/site-packages/velocity/__init__.py", line 2, in <module>
    from ._config import config
  File "/ccs/home/xjv/.local/lib/python3.6/site-packages/velocity/_config.py", line 11, in <module>
    class Config:
  File "/ccs/home/xjv/.local/lib/python3.6/site-packages/velocity/_config.py", line 17, in Config
    def set(self, item: str, value: int | bool | str | list | dict | None) -> None:
TypeError: unsupported operand type(s) for |: 'type' and 'type'
```

**Comment by AcerP-py** [comment]
Fixed in c44288709f50c56b55de5a3e41bf6ea57700d464 by requiring >= 3.10
